name: SonarQube
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
      - name: Cache Sonar packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Analyze ApiGateway
        env: { SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} }
        run: |
          cd ApiGateway
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=kanchanraiii_FlightBookingSystemMicroservice \
            -Dsonar.host.url=https://sonarcloud.io

      - name: Analyze BookingService
        env: { SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} }
        run: |
          cd BookingService
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=kanchanraiii_FlightBookingSystemMicroservice \
            -Dsonar.host.url=https://sonarcloud.io

      - name: Analyze FlightService
        env: { SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} }
        run: |
          cd FlightService
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=kanchanraiii_FlightBookingSystemMicroservice \
            -Dsonar.host.url=https://sonarcloud.io

      - name: Analyze ConfigServer
        env: { SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} }
        run: |
          cd ConfigServerFlightBooking
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=kanchanraiii_FlightBookingSystemMicroservice \
            -Dsonar.host.url=https://sonarcloud.io

      - name: Analyze Eureka
        env: { SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} }
        run: |
          cd FlightBookingEurekaServer
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=kanchanraiii_FlightBookingSystemMicroservice \
            -Dsonar.host.url=https://sonarcloud.io
